# Generated by Django 6.0.4 on 2026-07-19 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0002_game_game_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PointsShopItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('cost', models.PositiveIntegerField(default=100, verbose_name='Стоимость в очках')),
                ('icon', models.CharField(default='fa-star', max_length=40, verbose_name='FontAwesome icon')),
                ('is_active', models.BooleanField(default=True)),
                ('reward_type', models.CharField(choices=[('xp', 'Опыт профиля'), ('badge', 'Бейдж'), ('balance', 'Бонус на баланс')], default='xp', max_length=30)),
                ('reward_value', models.PositiveIntegerField(default=10)),
            ],
            options={
                'verbose_name': 'Товар Points Shop',
                'verbose_name_plural': 'Points Shop',
            },
        ),
        migrations.CreateModel(
            name='SaleEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('banner_color', models.CharField(default='#1a9fff', max_length=20)),
                ('extra_discount', models.PositiveIntegerField(default=0, help_text='Накладывается поверх скидки игры (макс. 90%)', verbose_name='Доп. скидка % на всё')),
            ],
            options={
                'verbose_name': 'Распродажа',
                'verbose_name_plural': 'Распродажи',
                'ordering': ['-starts_at'],
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('purchase', 'Покупка'), ('play', 'Играл'), ('achievement', 'Достижение'), ('friend', 'Друг'), ('review', 'Отзыв'), ('gift', 'Подарок'), ('level', 'Уровень'), ('status', 'Статус')], max_length=20)),
                ('text', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='games.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Активность',
                'verbose_name_plural': 'Лента активности',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GameNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('is_update', models.BooleanField(default=False, verbose_name='Обновление')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='games.game')),
            ],
            options={
                'verbose_name': 'Новость игры',
                'verbose_name_plural': 'Новости игр',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, max_length=250)),
                ('price_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('accepted', 'Принят'), ('declined', 'Отклонён'), ('cancelled', 'Отменён')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.game')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gifts_received', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gifts_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Подарок',
                'verbose_name_plural': 'Подарки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PointsPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_paid', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_purchases', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='steamplus.pointsshopitem')),
            ],
        ),
        migrations.CreateModel(
            name='DailyBonusClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_date', models.DateField()),
                ('points_awarded', models.PositiveIntegerField(default=0)),
                ('xp_awarded', models.PositiveIntegerField(default=0)),
                ('streak', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_bonuses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daily bonus',
                'verbose_name_plural': 'Daily bonuses',
                'ordering': ['-claim_date'],
                'unique_together': {('user', 'claim_date')},
            },
        ),
        migrations.CreateModel(
            name='DiscoverySkip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discovery_skips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'game')},
            },
        ),
        migrations.CreateModel(
            name='GameRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-score'],
                'unique_together': {('user', 'game')},
            },
        ),
        migrations.CreateModel(
            name='Playtime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutes', models.PositiveIntegerField(default=0, verbose_name='Минут сыграно')),
                ('last_played', models.DateTimeField(blank=True, null=True, verbose_name='Последний запуск')),
                ('sessions', models.PositiveIntegerField(default=0, verbose_name='Сессий')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playtimes', to='games.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playtimes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Время в игре',
                'verbose_name_plural': 'Время в играх',
                'ordering': ['-last_played'],
                'unique_together': {('user', 'game')},
            },
        ),
    ]
