# Generated by Django 5.2.13 on 2026-04-24 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_email_verified_profile_verification_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={},
        ),
        migrations.RemoveField(
            model_name='profile',
            name='email_verified',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='verification_code',
        ),
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('offline', 'Оффлайн'), ('online', 'Онлайн')], default='offline', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='xp',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='steam_level',
            field=models.IntegerField(default=0),
        ),
    ]
