# Generated by Django 6.0.4 on 2026-06-07 16:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_balance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, unique=True, verbose_name='Ключ сессии')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP адрес')),
                ('device_type', models.CharField(max_length=50, verbose_name='Тип устройства')),
                ('browser', models.CharField(max_length=100, verbose_name='Браузер')),
                ('os', models.CharField(max_length=100, verbose_name='Операционная система')),
                ('last_activity', models.DateTimeField(auto_now=True, verbose_name='Последняя активность')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Устройство пользователя',
                'verbose_name_plural': 'Устройства пользователей',
            },
        ),
    ]
