# Generated by Django 6.0.4 on 2026-06-07 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_userdevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdevice',
            name='city',
            field=models.CharField(default='Неизвестно', max_length=100, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='userdevice',
            name='country',
            field=models.CharField(default='Неизвестно', max_length=100, verbose_name='Страна'),
        ),
    ]
