# Generated by Django 6.0.4 on 2026-07-19 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_userdevice_city_userdevice_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='custom_status',
            field=models.CharField(blank=True, max_length=80, verbose_name='Кастомный статус'),
        ),
        migrations.AddField(
            model_name='profile',
            name='daily_streak',
            field=models.PositiveIntegerField(default=0, verbose_name='Серия daily'),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_daily_bonus',
            field=models.DateField(blank=True, null=True, verbose_name='Последний daily bonus'),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Был в сети'),
        ),
        migrations.AddField(
            model_name='profile',
            name='steam_points',
            field=models.PositiveIntegerField(default=0, verbose_name='Steam Points'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('offline', 'Оффлайн'), ('online', 'Онлайн'), ('away', 'Отошёл'), ('busy', 'Не беспокоить'), ('looking_to_play', 'Ищет игру'), ('looking_to_trade', 'Ищет обмен')], default='offline', max_length=20, verbose_name='Статус'),
        ),
    ]
