# Generated by Django 5.2.13 on 2026-04-23 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_inventoryitem_options_alter_item_options_and_more'),
        ('trades', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradeitem',
            name='trade',
        ),
        migrations.RemoveField(
            model_name='tradeitem',
            name='item',
        ),
        migrations.CreateModel(
            name='TradeOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('accepted', 'Принят'), ('declined', 'Отклонён'), ('cancelled', 'Отменён')], default='pending', max_length=20)),
                ('message', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_trade_offers', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_trade_offers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Предложение обмена',
                'verbose_name_plural': 'Предложения обмена',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TradeOfferItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_sender', models.BooleanField()),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventoryitem')),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_items', to='trades.tradeoffer')),
            ],
            options={
                'verbose_name': 'Предмет обмена',
                'verbose_name_plural': 'Предметы обмена',
            },
        ),
        migrations.DeleteModel(
            name='Trade',
        ),
        migrations.DeleteModel(
            name='TradeItem',
        ),
    ]
