# Generated by Django 5.2.13 on 2026-04-24 16:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0002_alter_inventoryitem_options_alter_item_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('active', 'Активен'), ('sold', 'Продан'), ('cancelled', 'Отменён')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sold_at', models.DateTimeField(blank=True, null=True)),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='market_purchases', to=settings.AUTH_USER_MODEL)),
                ('inventory_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='market_listing', to='inventory.inventoryitem')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Лот маркета',
                'verbose_name_plural': 'Лоты маркета',
                'ordering': ['-created_at'],
            },
        ),
    ]
