# Generated by Django 6.0.4 on 2026-07-21 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqarticle',
            name='slug',
            field=models.SlugField(allow_unicode=True, unique=True),
        ),
        migrations.AlterField(
            model_name='faqcategory',
            name='slug',
            field=models.SlugField(allow_unicode=True, unique=True),
        ),
    ]
