# Generated by Django 5.2.13 on 2026-04-26 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_inventoryitem_options_alter_item_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='show_in_profile',
            field=models.BooleanField(default=False, verbose_name='Показывать в профиле'),
        ),
    ]
