# Generated by Django 6.0.4 on 2026-05-28 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancerequest',
            name='click_paydoc_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID платежа Click'),
        ),
    ]
