# Generated by Django 5.2.13 on 2026-04-24 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_file',
            field=models.FileField(blank=True, null=True, upload_to='games/files/', verbose_name='Файл игры (.exe)'),
        ),
    ]
