# Generated by Django 6.0.4 on 2026-07-26 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_game_game_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='games/backgrounds/', verbose_name='Фон'),
        ),
        migrations.AlterField(
            model_name='game',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='games/headers/', verbose_name='Заглавное изображение'),
        ),
    ]
